### ISSUE TITLE
How to make button disabled when still had error

### ISSUE THREAD

**Issue by fjr619** [bhoomit11/ValidationHelper#1]
How to call `validationHelper.validateAll()` outside button, so i need make button disabled when still has error in form. Should i add textwatcher in every my edittext? or is there any other way?

**Comment by bhoomit11** [comment]
Hello @fjr619 thanks for the feedback
`validationHelper.validateAll()` simply will validate all of your validation you added in validationHelper class, now for your scenario if you want to check validation on type then what you can do is create a delay listener for edittext means after 400-500 millisecond of user stops writing you can call `validationHelper.validateAll()`
that way you can overcome your problem
